In [1]:
import pandas as pd
import sys
sys.path.append('..')
from python.c_limpieza.limpieza_datos import *

In [2]:
df_ventas = pd.read_csv('../dataset/raw/ventas.csv')
df_ventas.head()

,ordenID,productoID,UnitPrice,Quantity,NombreProducto,categoriaID,clienteID,fecha,NombreCategoria,TotalVenta,Mes
0,10248,11,14.0,12,Queso Cabrales,4,VINET,1996-07-04,Dairy Products,168.0,1996-07
1,10248,42,9.8,10,Singaporean Hokkien Fried Mee,5,VINET,1996-07-04,Grains/Cereals,98.0,1996-07
2,10248,72,34.8,5,Mozzarella di Giovanni,4,VINET,1996-07-04,Dairy Products,174.0,1996-07
3,10249,14,18.6,9,Tofu,7,TOMSP,1996-07-05,Produce,167.4,1996-07
4,10249,51,42.4,40,Manjimup Dried Apples,7,TOMSP,1996-07-05,Produce,1696.0,1996-07

In [3]:
# Correccción de tipo de datos 
#f_convertir_fechas(df_ventas, 'fecha')
f_convertir_fechas(df_ventas, 'fecha')

df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ordenID          2155 non-null   int64
 1   productoID       2155 non-null   int64
 2   UnitPrice        2155 non-null   float64
 3   Quantity         2155 non-null   int64
 4   NombreProducto   2155 non-null   object
 5   categoriaID      2155 non-null   int64
 6   clienteID        2155 non-null   object
 7   fecha            2155 non-null   datetime64[ns]
 8   NombreCategoria  2155 non-null   object
 9   TotalVenta       2155 non-null   float64
 10  Mes              2155 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(4), object(4)
memory usage: 185.3+ KB

In [4]:
# Creación de nueva columna (Mes)
df_ventas['Mes'] = df_ventas['fecha'].dt.to_period('M').astype(str)
df_ventas.head()

,ordenID,productoID,UnitPrice,Quantity,NombreProducto,categoriaID,clienteID,fecha,NombreCategoria,TotalVenta,Mes
0,10248,11,14.0,12,Queso Cabrales,4,VINET,1996-07-04,Dairy Products,168.0,1996-07
1,10248,42,9.8,10,Singaporean Hokkien Fried Mee,5,VINET,1996-07-04,Grains/Cereals,98.0,1996-07
2,10248,72,34.8,5,Mozzarella di Giovanni,4,VINET,1996-07-04,Dairy Products,174.0,1996-07
3,10249,14,18.6,9,Tofu,7,TOMSP,1996-07-05,Produce,167.4,1996-07
4,10249,51,42.4,40,Manjimup Dried Apples,7,TOMSP,1996-07-05,Produce,1696.0,1996-07

In [5]:
# Creamos una columna CategoriaVentas
df_ventas["CategoriaVentas"] = pd.cut(df_ventas["TotalVenta"], 
                               bins=[0, 100, 1000, 5000, 16000], 
                               labels=["Baja", "Media", "Alta", "Muy Alta"])

df_ventas.head()

,ordenID,productoID,UnitPrice,Quantity,NombreProducto,categoriaID,clienteID,fecha,NombreCategoria,TotalVenta,Mes,CategoriaVentas
0,10248,11,14.0,12,Queso Cabrales,4,VINET,1996-07-04,Dairy Products,168.0,1996-07,Media
1,10248,42,9.8,10,Singaporean Hokkien Fried Mee,5,VINET,1996-07-04,Grains/Cereals,98.0,1996-07,Baja
2,10248,72,34.8,5,Mozzarella di Giovanni,4,VINET,1996-07-04,Dairy Products,174.0,1996-07,Media
3,10249,14,18.6,9,Tofu,7,TOMSP,1996-07-05,Produce,167.4,1996-07,Media
4,10249,51,42.4,40,Manjimup Dried Apples,7,TOMSP,1996-07-05,Produce,1696.0,1996-07,Alta

In [6]:
# Validación final
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ordenID          2155 non-null   int64
 1   productoID       2155 non-null   int64
 2   UnitPrice        2155 non-null   float64
 3   Quantity         2155 non-null   int64
 4   NombreProducto   2155 non-null   object
 5   categoriaID      2155 non-null   int64
 6   clienteID        2155 non-null   object
 7   fecha            2155 non-null   datetime64[ns]
 8   NombreCategoria  2155 non-null   object
 9   TotalVenta       2155 non-null   float64
 10  Mes              2155 non-null   object
 11  CategoriaVentas  2155 non-null   category
dtypes: category(1), datetime64[ns](1), float64(2), int64(4), object(4)
memory usage: 187.6+ KB

In [7]:
df_ventas[['UnitPrice', 'Quantity', 'TotalVenta']].describe().round(2)

       UnitPrice  Quantity  TotalVenta
count    2155.00   2155.00     2155.00
mean       26.22     23.81      628.52
std        29.83     19.02     1036.47
min         2.00      1.00        4.80
25%        12.00     10.00      154.00
50%        18.40     20.00      360.00
75%        32.00     30.00      722.25
max       263.50    130.00    15810.00

In [8]:
# Revisamos nuevamente valores null
df_ventas.isnull().sum()

ordenID            0
productoID         0
UnitPrice          0
Quantity           0
NombreProducto     0
categoriaID        0
clienteID          0
fecha              0
NombreCategoria    0
TotalVenta         0
Mes                0
CategoriaVentas    0
dtype: int64

In [9]:
# Guardamos el Dataset limpio y transformado
df_ventas.to_csv('../dataset/procesado/ventas_limpio.csv', index = False)